BoxLayout
    orientation: 'vertical'
    BoxLayout
        orientation: 'vertical'
        Button
            text: 'Cheese $12.50'
        Button
            text: 'Laptop $912.95'
        Button
            text: 'Plant $4.75'
    BoxLayout
        size_hint_y: 0.5
        Label
        # Change this to a variable
            text: 'Total price $total_price'
        Button
            text: 'Reset'
